version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "3003:80"
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Testing
      MYSQL_DATABASE: demo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./employees.sql:/docker-entrypoint-initdb.d/employees.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pTesting || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
